### PR TITLE
New version by Bryce Steuer (squashed commits)

### PR DESCRIPTION
**Pull request by tuomas2**

### CODE REVIEW

**Comment by BryceSteuer** [comment]
What further exactly do you think should be done?

**Comment by tuomas2** [comment]
Hmm removed some files that were not used and then changed backslashes to slashes https://github.com/AndBible/andbible.github.io/commit/1344ac10071c996008365f29791eea87556f3fb9

**Comment by tuomas2** [comment]
But it's okay if it's easier for you to redo these changes.

**Comment by BryceSteuer** [comment]
I've pulled your changes already and formed a new branch. I can further change that branch if there are any areas of concern that need to be addressed before the final PR. I have a few things I know I need to change, but let me know if you see anything else.

**Pull request closed without merging**
