### PR TITLE
Improve/webpage upgrade

### PR DESCRIPTION
**Pull request by BryceSteuer**
Webpage upgrade. One thing still pending - new YouTube playlist. Main changes:

- Beautify header and add new logo
- Add icon to title tab
- expand on sidebar
- add new screenshots
- add statistics counter at a glance
- add footer with social media icons
- change fonts and colors

### CODE REVIEW

**Comment by tuomas2** [comment]
If we are using fontawesome I think we should not still include it's source code here.
Perhaps using cdn would be ok here.

**Comment by tuomas2** [comment]
I'm looking at this now. Will create a new PR based on this.

**Comment by BryceSteuer** [comment]
Ok, I added the CDN and it works fine.

**Comment by tuomas2** [comment]
Please pull my branch and continue there?

See https://github.com/AndBible/andbible.github.io/pull/3

**Comment by tuomas2** [comment]
I fixed couple of issues and removed unnecessary files

**Pull request closed without merging**
