### PR TITLE
Updated: Reviews, Lightbox, "And Bible" mentions

### PR DESCRIPTION
**Pull request by BryceSteuer**
I will add the final commits here for the review random functionality as I get them done.

### CODE REVIEW

**Comment by tuomas2** [comment]
I can already merge current changes now.

**Comment by timbze** [comment]
Looks like this wasn't merged to master

**Comment by tuomas2** [comment]
Ah, please make PRs towards master branch @BryceSteuer

**Comment by BryceSteuer** [comment]
Ok, this is toward the master
https://github.com/AndBible/andbible.github.io/pull/10

**Pull request merged**
